version: "2"

services:
  ghost:
    image: ghost:alpine
    volumes:
      - ./ghostdata:/var/lib/ghost/content
    environment:
      - url=${URL}
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghostdb
      - database__connection__password=${GHOSTDB_PASSWORD}
      - database__connection__database=ghostdb
      - VIRTUAL_HOST=${LETSENCRYPT_DOMAINS}
      - VIRTUAL_PORT=2368
      - LETSENCRYPT_HOST=${LETSENCRYPT_DOMAINS}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - mail__from=${MAIL_FROM}
      - mail__options__host=${MAIL_HOST}
      - mail__options__auth__user=${MAIL_USER}
      - mail__options__auth__pass=${MAIL_PASS}
      - mail__options__port=${MAIL_PORT}
      - mail__options__service=${MAIL_SERVICE}
      - mail__transport=${MAIL_TRANSPORT}
    networks:
      - ghost
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: ariaieboy/low-memory-mysql8:latest # or you can use: mysql:8.0
    volumes:
      - ./ghostdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOTDB_PASSWORD}
      - MYSQL_DATABASE=ghostdb
      - MYSQL_USER=ghostdb
      - MYSQL_PASSWORD=${GHOSTDB_PASSWORD}
    networks:
      - ghost
    restart: unless-stopped

  nginx-proxy:
    build: https://raw.githubusercontent.com/TaylorJadin/Ghost-docker-jps/main/Dockerfile
    volumes: 
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ghost
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    networks:
      - ghost
    restart: unless-stopped
  
#  Optional DB admin web interface, uncomment the next 4 lines if you want to use this temporarily
#  adminer:
#   image: adminer
#    ports:
#      - '8080:8080'

volumes:
  certs:

networks:
  ghost:
